# Moe global options

# List of any plugins to explicitly enable.
enable_plugins = [
    "musicbrainz",
    "bucket",
    "disc_and_track",
    "label_catalognum",
    "media_encoding",
    "organize_extras",
    "the",
    "year_reissue"
]

# Tells Moe where your music library resides.
library_path = "/home/alir/music-tagging-moe/library-tagged"

# Whether or not to always set an album’s date to its original_date if present.
original_date = false

# Alters the location of files in your library.
[move]

# Whether or not to convert all filesystem paths to ASCII.
asciify_paths = false

# Album filesystem path format relative to the global configuration option, library_path.
album_path = "{bucket(the(album.artist))}/{the(album.artist)}/{album.artist} - {album.title} ({year_reissue(album)}){label_catalognum(album)} [{media_encoding(album)}]"

# Track filesystem path format relative to album_path.
track_path = "{disc_dir_padded(track, album)}/{track.track_num:02d}. {track.title}{track.path.suffix}"

# Extra filesystem path format relative to album_path.
extra_path = "{organize_extras(extra)}"
