# Moe Configuration File
# Documentation: https://mrmoe.readthedocs.io/en/latest/

# Moe global options

# List of any plugins to explicitly enable.
enable_plugins = [
    "musicbrainz",

    "bucket",
    "disc_and_track",
    "label_catalognum",
    "media_encoding",
    "the",
    "year_reissue",

    "organize_extras",
    "filter_extras",

    "album_type",
    "album_art",
    "redoflacs_test",
    "redoflacs_compress",
]

library_path = "/home/alir/music-tagging-moe/library-tagged"
original_date = false

[move]
# Whether or not to convert all filesystem paths to ASCII.
asciify_paths = false

# Album filesystem path format relative to the global configuration option, library_path.
album_path = "{bucket(the(album.artist))}/{the(album.artist)}/{album.artist} - {album.title} ({year_reissue(album)}){label_catalognum(album)} [{media_encoding(album)}]"

# Track filesystem path format relative to album_path.
track_path = "{disc_dir_padded(track, album)}/{track.track_num:02d}. {track.title}{track.path.suffix}"

# Extra filesystem path format relative to album_path.
extra_path = "{organize_extras(extra)}"

[album_type]
compilation_album_path = "Compilations/{album.title} ({year_reissue(album)}){label_catalognum(album)} [{media_encoding(album)}]"
soundtrack_album_path = "Soundtracks/{album.title} ({year_reissue(album)}){label_catalognum(album)} [{media_encoding(album)}]"
classical_album_path = "Classical/{album.artist}/{album.title} ({year_reissue(album)}){label_catalognum(album)} [{media_encoding(album)}]"

[filter_extras]
text_editor = "kate"

[album_art]
image_viewer = "qimgv {image_path}"

[redoflacs_test]
global_jobs = 16

[redoflacs_compress]
global_jobs = 16
compression_jobs = 16
compression_threads = 2
