[project]
name = "moe-plugins"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moe>=2.3.0",
    "moe-musicbrainz>=1.0.2",
    "pillow>=11.2.1",
    "python3-discogs-client>=2.8",
]
